services:
  - type: web
    runtime: static
    name: roster
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_SENTRY_ENVIRONMENT
        value: production
        previewValue: preview
