import { supabase } from '@/lib/supabase';
import type { Tables, TablesInsert, TablesUpdate, Json } from '@/types/app.types';
import { throwIfSupabaseError, requireData, ValidationError } from '@/lib/errorHandler';
import { safeValidateEvent, validateCustomFields, type CustomField } from '@/lib/validation';
import { requireValidSession } from '@/lib/sessionValidator';
import { notificationService } from './notificationService';

/** Extended Event type with computed properties and properly typed custom_fields */
export interface Event extends Omit<Tables<'events'>, 'custom_fields'> {
  participant_count?: number;
  custom_fields: CustomField[];
  group_name?: string;
}

export type Label = Tables<'labels'>;

/**
 * Converts a database event record to the application Event type.
 * Validates and transforms custom_fields from JSON to typed CustomField array.
 * @param dbEvent - Raw event record from the database
 * @returns Typed Event object with validated custom_fields
 */
function dbEventToEvent(dbEvent: Tables<'events'>): Event {
  const validatedCustomFields = validateCustomFields(dbEvent.custom_fields);

  return {
    ...dbEvent,
    is_private: dbEvent.is_private ?? false,
    custom_fields: validatedCustomFields,
  };
}

/** Helper to get all participant user IDs for an event (for notifications) */
async function getParticipantUserIds(eventId: string): Promise<string[]> {
  const { data } = await supabase
    .from('participants')
    .select('user_id, claimed_by_user_id')
    .eq('event_id', eventId);

  if (!data) return [];

  const userIds = new Set<string>();
  for (const p of data) {
    const userId = p.user_id || p.claimed_by_user_id;
    if (userId) userIds.add(userId);
  }
  return Array.from(userIds);
}

export const eventService = {
  /**
   * Retrieves all events created by an organizer with participant counts and group names.
   * Uses LEFT JOINs to fetch related data in a single query.
   * @param organizerId - UUID of the organizer
   * @returns Events sorted by creation date (newest first)
   * @throws Error if the database query fails
   */
  async getEventsByOrganizer(organizerId: string): Promise<Event[]> {
    const { data: eventsData, error: eventsError } = await supabase
      .from('events')
      .select(
        `
        *,
        participants!left(id),
        groups!left(name)
      `
      )
      .eq('organizer_id', organizerId)
      .order('created_at', { ascending: false });

    const data = throwIfSupabaseError({ data: eventsData, error: eventsError });

    if (!data) return [];

    return data.map((event) => {
      const participantCount = Array.isArray(event.participants)
        ? event.participants.filter((p) => p !== null).length
        : 0;

      const groupName =
        event.groups && !Array.isArray(event.groups) ? event.groups.name : undefined;

      const { participants, groups, ...eventWithoutJoins } = event as Tables<'events'> & {
        participants: Array<{ id: string } | null>;
        groups: { name: string } | null;
      };
      void participants;
      void groups;

      return {
        ...dbEventToEvent(eventWithoutJoins),
        participant_count: participantCount,
        group_name: groupName,
      };
    });
  },

  /**
   * Retrieves a single event by its ID.
   * @param eventId - UUID of the event
   * @returns The event with validated custom_fields
   * @throws Error if the event is not found or query fails
   */
  async getEventById(eventId: string): Promise<Event> {
    const { data, error } = await supabase.from('events').select('*').eq('id', eventId).single();

    throwIfSupabaseError({ data, error });
    return dbEventToEvent(requireData(data, 'get event'));
  },

  /**
   * Creates a new event with validated data.
   * Requires an authenticated session. ID is auto-generated by the database.
   * @param event - Event data without id, created_at, or participant_count
   * @returns The created event with generated ID
   * @throws ValidationError if event data is invalid
   * @throws Error if session is invalid or database insert fails
   */
  async createEvent(event: Omit<Event, 'id' | 'created_at' | 'participant_count'>): Promise<Event> {
    await requireValidSession();

    const validationResult = safeValidateEvent({
      ...event,
      created_at: new Date().toISOString(),
    });

    if (!validationResult.success) {
      const errorMessages =
        validationResult.error?.issues
          ?.map((e) => `${e.path?.join('.')}: ${e.message}`)
          .join(', ') || 'Unknown validation error';
      throw new ValidationError(
        `Invalid event data: ${errorMessages}`,
        'Please check your input and try again'
      );
    }

    const insertData: TablesInsert<'events'> = {
      organizer_id: event.organizer_id,
      name: event.name.trim(),
      description: event.description,
      datetime: event.datetime,
      end_datetime: event.end_datetime,
      location: event.location,
      is_private: event.is_private ?? false,
      custom_fields: event.custom_fields as unknown as Json,
      parent_event_id: event.parent_event_id,
      max_participants: event.max_participants,
      group_id: event.group_id,
    };

    const { data, error } = await supabase.from('events').insert(insertData).select().single();

    throwIfSupabaseError({ data, error });
    return dbEventToEvent(requireData(data, 'create event'));
  },

  /**
   * Updates an existing event with partial data.
   * Requires an authenticated session. Only provided fields are updated.
   * @param eventId - UUID of the event to update
   * @param updates - Partial event data to apply
   * @returns The updated event
   * @throws Error if session is invalid or event not found
   */
  async updateEvent(eventId: string, updates: Partial<Event>): Promise<Event> {
    await requireValidSession();

    // Get old event data to track changes for notifications
    const oldEvent = await this.getEventById(eventId);

    const updateData: TablesUpdate<'events'> = {};

    if (updates.name !== undefined) updateData.name = updates.name;
    if (updates.description !== undefined) updateData.description = updates.description;
    if (updates.datetime !== undefined) updateData.datetime = updates.datetime;
    if (updates.end_datetime !== undefined) updateData.end_datetime = updates.end_datetime;
    if (updates.location !== undefined) updateData.location = updates.location;
    if (updates.is_private !== undefined) updateData.is_private = updates.is_private;
    if (updates.max_participants !== undefined)
      updateData.max_participants = updates.max_participants;
    if (updates.custom_fields !== undefined)
      updateData.custom_fields = updates.custom_fields as unknown as Json;
    if (updates.group_id !== undefined) updateData.group_id = updates.group_id;

    const { data, error } = await supabase
      .from('events')
      .update(updateData)
      .eq('id', eventId)
      .select()
      .single();

    throwIfSupabaseError({ data, error });
    const updated = dbEventToEvent(requireData(data, 'update event'));

    // Track changes for notification (only significant fields)
    const changes: string[] = [];
    if (oldEvent.name !== updated.name) changes.push('title');
    if (oldEvent.datetime !== updated.datetime) changes.push('date/time');
    if (oldEvent.end_datetime !== updated.end_datetime) changes.push('end time');
    if (oldEvent.location !== updated.location) changes.push('location');
    if (oldEvent.description !== updated.description) changes.push('description');

    // Queue event_updated notifications if there were meaningful changes
    if (changes.length > 0) {
      getParticipantUserIds(eventId)
        .then((participantUserIds) => {
          notificationService
            .queueEventUpdated({
              organizerId: updated.organizer_id,
              eventId: updated.id,
              eventName: updated.name,
              changes,
              participantUserIds,
            })
            .catch((e) => console.error('Failed to queue event updated notifications:', e));
        })
        .catch((e) => console.error('Failed to get participant user IDs:', e));
    }

    return updated;
  },

  /**
   * Deletes an event by ID. Cascades to related participants and labels.
   * Requires an authenticated session.
   * @param eventId - UUID of the event to delete
   * @throws Error if session is invalid or deletion fails
   */
  async deleteEvent(eventId: string): Promise<void> {
    await requireValidSession();

    // Get event info and participant user IDs BEFORE deleting
    const event = await this.getEventById(eventId);
    const participantUserIds = await getParticipantUserIds(eventId);

    // Queue event_cancelled notifications BEFORE deleting
    // (fire and forget - don't block on this)
    notificationService
      .queueEventCancelled({
        organizerId: event.organizer_id,
        eventName: event.name,
        participantUserIds,
      })
      .catch((e) => console.error('Failed to queue event cancelled notifications:', e));

    const { data, error } = await supabase.from('events').delete().eq('id', eventId);

    throwIfSupabaseError({ data, error });
  },

  /**
   * Creates a copy of an existing event with its labels.
   * The duplicated event has "(Copy)" appended to its name and references the original via parent_event_id.
   * Requires an authenticated session.
   * @param eventId - UUID of the event to duplicate
   * @param organizerId - UUID of the organizer creating the copy
   * @returns The newly created duplicate event
   * @throws Error if original event not found or duplication fails
   */
  async duplicateEvent(eventId: string, organizerId: string): Promise<Event> {
    await requireValidSession();

    const { data: originalEvent, error: fetchError } = await supabase
      .from('events')
      .select('*')
      .eq('id', eventId)
      .single();

    throwIfSupabaseError({ data: originalEvent, error: fetchError });
    const original = requireData(originalEvent, 'get original event');

    const insertData: TablesInsert<'events'> = {
      organizer_id: organizerId,
      name: `${original.name} (Copy)`,
      description: original.description,
      datetime: original.datetime,
      end_datetime: original.end_datetime,
      location: original.location,
      custom_fields: original.custom_fields,
      parent_event_id: original.id,
      is_private: original.is_private,
      max_participants: original.max_participants,
      group_id: original.group_id,
    };

    const { data: newEvent, error: createError } = await supabase
      .from('events')
      .insert(insertData)
      .select()
      .single();

    throwIfSupabaseError({ data: newEvent, error: createError });
    const created = requireData(newEvent, 'duplicate event');

    const { data: labels } = await supabase.from('labels').select('*').eq('event_id', eventId);

    if (labels && labels.length > 0) {
      const labelInserts: TablesInsert<'labels'>[] = labels.map((label) => ({
        event_id: created.id,
        name: label.name,
        color: label.color,
      }));

      await supabase.from('labels').insert(labelInserts);
    }

    return dbEventToEvent(created);
  },

  /**
   * Retrieves all public (non-private) events sorted by datetime.
   * Does not require authentication.
   * @returns Array of public events sorted chronologically
   */
  async getPublicEvents(): Promise<Event[]> {
    const { data, error } = await supabase
      .from('events')
      .select('*')
      .eq('is_private', false)
      .order('datetime', { ascending: true });

    return (throwIfSupabaseError({ data, error }) || []).map(dbEventToEvent);
  },

  /**
   * Retrieves all events where a user is registered as a participant.
   * Uses INNER JOIN to filter by user participation and a separate query to get accurate participant counts.
   * @param userId - UUID of the user
   * @returns Events with participant counts and group names, sorted by creation date
   * @throws Error if database query fails
   */
  async getEventsByParticipant(userId: string): Promise<Event[]> {
    const { data: eventsData, error: eventsError } = await supabase
      .from('events')
      .select(
        `
        *,
        participants!inner(id, user_id),
        groups!left(name)
      `
      )
      .eq('participants.user_id', userId)
      .order('created_at', { ascending: false });

    const events = throwIfSupabaseError({ data: eventsData, error: eventsError });

    if (!events || events.length === 0) return [];

    const eventIds = events.map((e) => e.id);
    const { data: allParticipants, error: participantsError } = await supabase
      .from('participants')
      .select('event_id, id')
      .in('event_id', eventIds);

    throwIfSupabaseError({ data: allParticipants, error: participantsError });

    const participantCountMap = new Map<string, number>();
    if (allParticipants) {
      allParticipants.forEach((p) => {
        const count = participantCountMap.get(p.event_id) || 0;
        participantCountMap.set(p.event_id, count + 1);
      });
    }

    return events.map((event) => {
      const participantCount = participantCountMap.get(event.id) || 0;
      const groupName =
        event.groups && !Array.isArray(event.groups) ? event.groups.name : undefined;

      const { participants, groups, ...eventWithoutJoins } = event as Tables<'events'> & {
        participants: Array<{ id: string } | null>;
        groups: { name: string } | null;
      };
      void participants;
      void groups;

      return {
        ...dbEventToEvent(eventWithoutJoins),
        participant_count: participantCount,
        group_name: groupName,
      };
    });
  },
};
