import { supabase } from '@/lib/supabase';
import type { Tables, TablesInsert, TablesUpdate } from '@/types/app.types';
import { errorHandler, ValidationError } from '@/lib/errorHandler';

// Extended Group type with additional computed properties
export interface Group extends Tables<'groups'> {
  event_count?: number;
  participant_count?: number;
}

export interface GroupParticipant extends Tables<'participants'> {
  event: {
    id: string;
    name: string;
  };
  group_joined_at: string;
}

export interface GroupStats {
  event_count: number;
  participant_count: number;
  total_registrations: number;
}

// Validation function for group data
function validateGroupData(group: Partial<Group>): void {
  if (group.name !== undefined) {
    if (!group.name || group.name.trim().length === 0) {
      throw new ValidationError('Group name is required', 'Please enter a group name');
    }
    if (group.name.length > 200) {
      throw new ValidationError(
        'Group name is too long',
        'Group name must be 200 characters or less'
      );
    }
  }

  if (group.description !== undefined && group.description !== null) {
    if (group.description.length > 2000) {
      throw new ValidationError(
        'Group description is too long',
        'Description must be 2000 characters or less'
      );
    }
  }
}

export const groupService = {
  async getGroupsByOrganizer(organizerId: string): Promise<Group[]> {
    // Get groups with event and participant counts in a single query
    const { data: groupsData, error: groupsError } = await supabase
      .from('groups')
      .select(
        `
        *,
        events!left(id),
        group_participants!left(id)
      `
      )
      .eq('organizer_id', organizerId)
      .order('created_at', { ascending: false });

    if (groupsError) throw errorHandler.fromSupabaseError(groupsError);

    if (!groupsData) return [];

    return groupsData.map((group) => {
      // Count events and participants
      const eventCount = Array.isArray(group.events)
        ? group.events.filter((e) => e !== null).length
        : 0;
      const participantCount = Array.isArray(group.group_participants)
        ? group.group_participants.filter((p) => p !== null).length
        : 0;

      // Remove the joined arrays from the group object before processing
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const {
        events: _,
        group_participants: __,
        ...groupWithoutJoins
      } = group as Tables<'groups'> & {
        events: Array<{ id: string } | null>;
        group_participants: Array<{ id: string } | null>;
      };

      return {
        ...groupWithoutJoins,
        event_count: eventCount,
        participant_count: participantCount,
      };
    });
  },

  async getGroupById(groupId: string): Promise<Group> {
    const { data, error } = await supabase.from('groups').select('*').eq('id', groupId).single();

    if (error) throw error;
    if (!data) throw new Error('Group not found');

    return data;
  },

  async createGroup(
    group: Omit<Group, 'id' | 'created_at' | 'event_count' | 'participant_count'>
  ): Promise<Group> {
    // Validate input data
    validateGroupData(group);

    const insertData: TablesInsert<'groups'> = {
      // id will be auto-generated by database nanoid() function
      organizer_id: group.organizer_id,
      name: group.name.trim(),
      description: group.description,
      is_private: group.is_private ?? false,
    };

    const { data, error } = await supabase.from('groups').insert(insertData).select().single();

    if (error) throw error;
    if (!data) throw new Error('Failed to create group');

    return data;
  },

  async updateGroup(groupId: string, updates: Partial<Group>): Promise<Group> {
    // Validate input data
    validateGroupData(updates);

    const updateData: TablesUpdate<'groups'> = {};

    if (updates.name !== undefined) updateData.name = updates.name.trim();
    if (updates.description !== undefined) updateData.description = updates.description;
    if (updates.is_private !== undefined) updateData.is_private = updates.is_private;

    const { data, error } = await supabase
      .from('groups')
      .update(updateData)
      .eq('id', groupId)
      .select()
      .single();

    if (error) throw error;
    if (!data) throw new Error('Failed to update group');

    return data;
  },

  async deleteGroup(groupId: string): Promise<void> {
    const { error } = await supabase.from('groups').delete().eq('id', groupId);

    if (error) throw error;
  },

  async getGroupEvents(
    groupId: string
  ): Promise<Array<Tables<'events'> & { participant_count?: number }>> {
    // Get events in this group with participant counts
    const { data: eventsData, error: eventsError } = await supabase
      .from('events')
      .select(
        `
        *,
        participants!left(id)
      `
      )
      .eq('group_id', groupId)
      .order('datetime', { ascending: true });

    if (eventsError) throw errorHandler.fromSupabaseError(eventsError);

    if (!eventsData) return [];

    return eventsData.map((event) => {
      // Count the participants
      const participantCount = Array.isArray(event.participants)
        ? event.participants.filter((p) => p !== null).length
        : 0;

      // Remove the participants array from the event object before processing
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { participants: _, ...eventWithoutParticipants } = event as Tables<'events'> & {
        participants: Array<{ id: string } | null>;
      };

      return {
        ...eventWithoutParticipants,
        participant_count: participantCount,
      };
    });
  },

  async getGroupParticipants(groupId: string): Promise<GroupParticipant[]> {
    // Get all participants in this group with their event context
    const { data: participantsData, error: participantsError } = await supabase
      .from('group_participants')
      .select(
        `
        joined_at,
        participants!inner (
          *,
          events!inner (
            id,
            name
          )
        )
      `
      )
      .eq('group_id', groupId)
      .order('joined_at', { ascending: false });

    if (participantsError) throw errorHandler.fromSupabaseError(participantsError);

    if (!participantsData) return [];

    return participantsData.map((item) => {
      const participant = item.participants as any; // eslint-disable-line @typescript-eslint/no-explicit-any
      const event = participant.events;

      return {
        ...participant,
        event: Array.isArray(event) ? event[0] : event,
        group_joined_at: item.joined_at,
      };
    });
  },

  async getGroupStats(groupId: string): Promise<GroupStats> {
    // Get event count
    const { count: eventCount, error: eventError } = await supabase
      .from('events')
      .select('*', { count: 'exact', head: true })
      .eq('group_id', groupId);

    if (eventError) throw errorHandler.fromSupabaseError(eventError);

    // Get unique participant count (group members)
    const { count: participantCount, error: participantError } = await supabase
      .from('group_participants')
      .select('*', { count: 'exact', head: true })
      .eq('group_id', groupId);

    if (participantError) throw errorHandler.fromSupabaseError(participantError);

    // Get total registrations across all events in group
    const { count: totalRegistrations, error: registrationsError } = await supabase
      .from('participants')
      .select('event_id, events!inner(group_id)', { count: 'exact', head: true })
      .eq('events.group_id', groupId);

    if (registrationsError) throw errorHandler.fromSupabaseError(registrationsError);

    return {
      event_count: eventCount || 0,
      participant_count: participantCount || 0,
      total_registrations: totalRegistrations || 0,
    };
  },

  async addParticipantToGroup(groupId: string, participantId: string): Promise<void> {
    const insertData: TablesInsert<'group_participants'> = {
      group_id: groupId,
      participant_id: participantId,
    };

    const { error } = await supabase.from('group_participants').insert(insertData);

    if (error) {
      // Ignore unique constraint violations (participant already in group)
      if (error.code !== '23505') {
        throw error;
      }
    }
  },

  async removeParticipantFromGroup(groupId: string, participantId: string): Promise<void> {
    const { error } = await supabase
      .from('group_participants')
      .delete()
      .eq('group_id', groupId)
      .eq('participant_id', participantId);

    if (error) throw error;
  },

  async getParticipantGroups(participantId: string): Promise<Group[]> {
    // Get all groups that a participant belongs to
    const { data: groupData, error: groupError } = await supabase
      .from('group_participants')
      .select(
        `
        groups!inner (*)
      `
      )
      .eq('participant_id', participantId);

    if (groupError) throw errorHandler.fromSupabaseError(groupError);

    if (!groupData) return [];

    return groupData.map((item) => {
      const group = item.groups as any; // eslint-disable-line @typescript-eslint/no-explicit-any
      return Array.isArray(group) ? group[0] : group;
    });
  },
};
