import { supabase } from '@/lib/supabase';
import type { Tables, TablesInsert, TablesUpdate } from '@/types/supabase';
import { errorHandler, ValidationError } from '@/lib/errorHandler';
import { requireValidSession } from '@/lib/sessionValidator';

// Extended Group type with additional computed properties
export interface Group extends Tables<'groups'> {
  event_count?: number;
  participant_count?: number;
}

export interface GroupParticipant extends Tables<'participants'> {
  event: {
    id: string;
    name: string;
  };
  group_joined_at: string;
}

export interface GroupContact {
  id: string;
  name: string;
  email: string | null;
  user_id: string | null;
  first_seen: string;
}

// Internal interfaces for the nested Supabase query results
interface GroupParticipantQueryResult {
  joined_at: string;
  participants: Tables<'participants'> & {
    events:
      | {
          id: string;
          name: string;
        }
      | Array<{
          id: string;
          name: string;
        }>;
  };
}

interface EventWithParticipants extends Tables<'events'> {
  participants: Array<{ id: string } | null>;
}

interface GroupQueryResult {
  groups: Tables<'groups'> | Array<Tables<'groups'>>;
}

interface GroupParticipantStatsQueryResult {
  participants: {
    user_id: string | null;
    email: string | null;
    id: string;
  };
}

export interface GroupStats {
  event_count: number;
  participant_count: number;
  total_registrations: number;
}

export type GroupAdmin = Tables<'group_admins'>;

// Validation function for group data
function validateGroupData(group: Partial<Group>): void {
  if (group.name !== undefined) {
    if (!group.name || group.name.trim().length === 0) {
      throw new ValidationError('Group name is required', 'Please enter a group name');
    }
    if (group.name.length > 200) {
      throw new ValidationError(
        'Group name is too long',
        'Group name must be 200 characters or less'
      );
    }
  }

  if (group.description !== undefined && group.description !== null) {
    if (group.description.length > 2000) {
      throw new ValidationError(
        'Group description is too long',
        'Description must be 2000 characters or less'
      );
    }
  }
}

export const groupService = {
  async getGroupsByOrganizer(organizerId: string): Promise<Group[]> {
    // Get groups without counts first
    const { data: groupsData, error: groupsError } = await supabase
      .from('groups')
      .select('*')
      .eq('organizer_id', organizerId)
      .order('created_at', { ascending: false });

    if (groupsError) throw errorHandler.fromSupabaseError(groupsError);

    if (!groupsData) return [];

    // Get accurate counts for each group (deduplicating participants)
    const groupsWithCounts = await Promise.all(
      groupsData.map(async (group) => {
        // Get event count
        const { count: eventCount, error: eventError } = await supabase
          .from('events')
          .select('*', { count: 'exact', head: true })
          .eq('group_id', group.id);

        if (eventError) throw errorHandler.fromSupabaseError(eventError);

        // Get unique participant count (avoiding duplicates)
        const { data: groupParticipantsData, error: participantError } = await supabase
          .from('group_participants')
          .select(
            `
            participants!inner (
              user_id,
              email,
              id
            )
          `
          )
          .eq('group_id', group.id);

        if (participantError) throw errorHandler.fromSupabaseError(participantError);

        // Deduplicate participants by stable identifiers
        const uniqueParticipants = new Set<string>();
        groupParticipantsData?.forEach((item: GroupParticipantStatsQueryResult) => {
          const participant = item.participants;
          const stableKey = participant.user_id || participant.email || participant.id;
          uniqueParticipants.add(stableKey);
        });

        return {
          ...group,
          event_count: eventCount || 0,
          participant_count: uniqueParticipants.size,
        };
      })
    );

    return groupsWithCounts;
  },

  async getGroupById(groupId: string): Promise<Group> {
    const { data, error } = await supabase.from('groups').select('*').eq('id', groupId).single();

    if (error) throw error;
    if (!data) throw new Error('Group not found');

    return data;
  },

  async createGroup(
    group: Omit<Group, 'id' | 'created_at' | 'event_count' | 'participant_count'>
  ): Promise<Group> {
    // Validate session before creating group
    await requireValidSession();

    // Validate input data
    validateGroupData(group);

    const insertData: TablesInsert<'groups'> = {
      // id will be auto-generated by database nanoid() function
      organizer_id: group.organizer_id,
      name: group.name.trim(),
      description: group.description,
      is_private: group.is_private ?? false,
    };

    const { data, error } = await supabase.from('groups').insert(insertData).select().single();

    if (error) throw error;
    if (!data) throw new Error('Failed to create group');

    return data;
  },

  async updateGroup(groupId: string, updates: Partial<Group>): Promise<Group> {
    // Validate session before updating group
    await requireValidSession();

    // Validate input data
    validateGroupData(updates);

    const updateData: TablesUpdate<'groups'> = {};

    if (updates.name !== undefined) updateData.name = updates.name.trim();
    if (updates.description !== undefined) updateData.description = updates.description;
    if (updates.is_private !== undefined) updateData.is_private = updates.is_private;

    const { data, error } = await supabase
      .from('groups')
      .update(updateData)
      .eq('id', groupId)
      .select()
      .single();

    if (error) throw error;
    if (!data) throw new Error('Failed to update group');

    return data;
  },

  async deleteGroup(groupId: string, deleteEvents: boolean = false): Promise<void> {
    // Validate session before deleting group
    await requireValidSession();

    if (deleteEvents) {
      // Delete all events in the group first
      const { error: eventsError } = await supabase.from('events').delete().eq('group_id', groupId);

      if (eventsError) throw eventsError;
    } else {
      // Unassociate events from the group (set group_id to null)
      const { error: eventsError } = await supabase
        .from('events')
        .update({ group_id: null })
        .eq('group_id', groupId);

      if (eventsError) throw eventsError;
    }

    // Now delete the group
    const { error } = await supabase.from('groups').delete().eq('id', groupId);

    if (error) throw error;
  },

  async getGroupEvents(
    groupId: string
  ): Promise<Array<Tables<'events'> & { participant_count?: number }>> {
    // Get events in this group with participant counts
    const { data: eventsData, error: eventsError } = await supabase
      .from('events')
      .select(
        `
        *,
        participants!left(id)
      `
      )
      .eq('group_id', groupId)
      .order('datetime', { ascending: true });

    if (eventsError) throw errorHandler.fromSupabaseError(eventsError);

    if (!eventsData) return [];

    return eventsData.map((event: EventWithParticipants) => {
      // Count the participants
      const participantCount = Array.isArray(event.participants)
        ? event.participants.filter((p) => p !== null).length
        : 0;

      // Remove the participants array from the event object before processing
      const { participants, ...eventWithoutParticipants } = event;
      void participants;

      return {
        ...eventWithoutParticipants,
        participant_count: participantCount,
      };
    });
  },

  async getGroupParticipants(groupId: string): Promise<GroupParticipant[]> {
    // Get all participants in this group with their event context
    const { data: participantsData, error: participantsError } = await supabase
      .from('group_participants')
      .select(
        `
        joined_at,
        participants!inner (
          *,
          events!inner (
            id,
            name
          )
        )
      `
      )
      .eq('group_id', groupId)
      .order('joined_at', { ascending: false });

    if (participantsError) throw errorHandler.fromSupabaseError(participantsError);

    if (!participantsData) return [];

    // Deduplicate participants by stable identifiers (user_id or email)
    // to avoid showing the same person multiple times
    const uniqueParticipants = new Map<string, GroupParticipant>();

    participantsData.forEach((item: GroupParticipantQueryResult) => {
      const participant = item.participants;
      const event = participant.events;

      // Create a stable key: use user_id if available, otherwise email
      const stableKey = participant.user_id || participant.email || participant.id;

      // Only keep the earliest membership record for each unique person
      const existing = uniqueParticipants.get(stableKey);
      const joinedAt = new Date(item.joined_at).getTime();

      if (!existing || joinedAt < new Date(existing.group_joined_at).getTime()) {
        uniqueParticipants.set(stableKey, {
          ...participant,
          event: Array.isArray(event) ? event[0] : event,
          group_joined_at: item.joined_at,
        });
      }
    });

    return Array.from(uniqueParticipants.values()).sort(
      (a, b) => new Date(b.group_joined_at).getTime() - new Date(a.group_joined_at).getTime()
    );
  },

  async getGroupStats(groupId: string): Promise<GroupStats> {
    // Get event count
    const { count: eventCount, error: eventError } = await supabase
      .from('events')
      .select('*', { count: 'exact', head: true })
      .eq('group_id', groupId);

    if (eventError) throw errorHandler.fromSupabaseError(eventError);

    // Get unique participant count (group members) by deduplicating by user_id/email
    const { data: groupParticipantsData, error: participantError } = await supabase
      .from('group_participants')
      .select(
        `
        participants!inner (
          user_id,
          email,
          id
        )
      `
      )
      .eq('group_id', groupId);

    if (participantError) throw errorHandler.fromSupabaseError(participantError);

    // Deduplicate participants by stable identifiers
    const uniqueParticipants = new Set<string>();
    groupParticipantsData?.forEach((item: GroupParticipantStatsQueryResult) => {
      const participant = item.participants;
      const stableKey = participant.user_id || participant.email || participant.id;
      uniqueParticipants.add(stableKey);
    });

    const participantCount = uniqueParticipants.size;

    // Get total registrations across all events in group
    const { count: totalRegistrations, error: registrationsError } = await supabase
      .from('participants')
      .select('event_id, events!inner(group_id)', { count: 'exact', head: true })
      .eq('events.group_id', groupId);

    if (registrationsError) throw errorHandler.fromSupabaseError(registrationsError);

    return {
      event_count: eventCount || 0,
      participant_count: participantCount,
      total_registrations: totalRegistrations || 0,
    };
  },

  async addParticipantToGroup(groupId: string, participantId: string): Promise<void> {
    // First get the participant's stable identifiers
    const { data: participantData, error: participantError } = await supabase
      .from('participants')
      .select('user_id, email')
      .eq('id', participantId)
      .single();

    if (participantError) throw errorHandler.fromSupabaseError(participantError);
    if (!participantData) throw new Error('Participant not found');

    // Insert using stable identifiers to prevent duplicates
    const insertData: TablesInsert<'group_participants'> = {
      group_id: groupId,
      participant_id: participantId,
      user_id: participantData.user_id,
      guest_email: participantData.user_id ? null : participantData.email,
    };

    const { error } = await supabase.from('group_participants').insert(insertData);

    if (error) {
      // Ignore unique constraint violations (participant already in group)
      if (error.code !== '23505') {
        throw errorHandler.fromSupabaseError(error);
      }
    }
  },

  async getAllContactsFromGroups(organizerId: string): Promise<GroupContact[]> {
    // Get all groups for this organizer
    const { data: groups, error: groupsError } = await supabase
      .from('groups')
      .select('id')
      .eq('organizer_id', organizerId);

    if (groupsError) throw errorHandler.fromSupabaseError(groupsError);
    if (!groups || groups.length === 0) return [];

    const groupIds = groups.map((g) => g.id);

    // Get all participants from these groups
    const { data: groupParticipantsData, error: participantsError } = await supabase
      .from('group_participants')
      .select(
        `
        joined_at,
        participants!inner (
          id,
          name,
          email,
          user_id
        )
      `
      )
      .in('group_id', groupIds)
      .order('joined_at', { ascending: true });

    if (participantsError) throw errorHandler.fromSupabaseError(participantsError);
    if (!groupParticipantsData) return [];

    // Deduplicate by stable identifier (user_id or email)
    const contactsMap = new Map<string, GroupContact>();

    groupParticipantsData.forEach(
      (item: {
        joined_at: string;
        participants: { id: string; name: string; email: string | null; user_id: string | null };
      }) => {
        const participant = item.participants;
        const stableKey = participant.user_id || participant.email || participant.id;

        // Only keep the first occurrence (earliest joined_at)
        if (!contactsMap.has(stableKey)) {
          contactsMap.set(stableKey, {
            id: participant.id,
            name: participant.name,
            email: participant.email,
            user_id: participant.user_id,
            first_seen: item.joined_at,
          });
        }
      }
    );

    // Return sorted by name
    return Array.from(contactsMap.values()).sort((a, b) => a.name.localeCompare(b.name));
  },

  async removeParticipantFromGroup(groupId: string, participantId: string): Promise<void> {
    // First get the participant's stable identifiers to remove by the correct key
    const { data: participantData, error: participantError } = await supabase
      .from('participants')
      .select('user_id, email')
      .eq('id', participantId)
      .single();

    if (participantError) throw errorHandler.fromSupabaseError(participantError);
    if (!participantData) throw new Error('Participant not found');

    // Remove using stable identifiers
    let deleteQuery = supabase.from('group_participants').delete().eq('group_id', groupId);

    if (participantData.user_id) {
      deleteQuery = deleteQuery.eq('user_id', participantData.user_id);
    } else if (participantData.email) {
      deleteQuery = deleteQuery.eq('guest_email', participantData.email);
    } else {
      throw new Error('Cannot remove participant: no stable identifier found');
    }

    const { error } = await deleteQuery;

    if (error) throw errorHandler.fromSupabaseError(error);
  },

  async getParticipantGroups(participantId: string): Promise<Group[]> {
    // First get the participant's stable identifiers
    const { data: participantData, error: participantError } = await supabase
      .from('participants')
      .select('user_id, email')
      .eq('id', participantId)
      .single();

    if (participantError) throw errorHandler.fromSupabaseError(participantError);
    if (!participantData) return [];

    // Get all groups that this person belongs to (using stable identifiers)
    let groupQuery = supabase.from('group_participants').select(
      `
        groups!inner (*)
      `
    );

    if (participantData.user_id) {
      groupQuery = groupQuery.eq('user_id', participantData.user_id);
    } else if (participantData.email) {
      groupQuery = groupQuery.eq('guest_email', participantData.email);
    } else {
      // No stable identifier found, return empty array
      return [];
    }

    const { data: groupData, error: groupError } = await groupQuery;

    if (groupError) throw errorHandler.fromSupabaseError(groupError);

    if (!groupData) return [];

    return groupData.map((item: GroupQueryResult) => {
      const group = item.groups;
      return Array.isArray(group) ? group[0] : group;
    });
  },

  async isGroupAdmin(groupId: string, userId: string): Promise<boolean> {
    // Check if user is the group owner
    const { data: group, error: groupError } = await supabase
      .from('groups')
      .select('organizer_id')
      .eq('id', groupId)
      .single();

    if (groupError) throw errorHandler.fromSupabaseError(groupError);
    if (!group) return false;

    // User is admin if they are the owner
    if (group.organizer_id === userId) return true;

    // Check if user is in the group_admins table
    const { data: adminRecord, error: adminError } = await supabase
      .from('group_admins')
      .select('id')
      .eq('group_id', groupId)
      .eq('user_id', userId)
      .maybeSingle();

    if (adminError) throw errorHandler.fromSupabaseError(adminError);

    return adminRecord !== null;
  },

  async addGroupAdmin(groupId: string, userId: string): Promise<void> {
    const { error } = await supabase.from('group_admins').insert({
      group_id: groupId,
      user_id: userId,
    });

    if (error) {
      // Ignore unique constraint violations (admin already exists)
      if (error.code !== '23505') {
        throw errorHandler.fromSupabaseError(error);
      }
    }
  },

  async removeGroupAdmin(groupId: string, userId: string): Promise<void> {
    const { error } = await supabase
      .from('group_admins')
      .delete()
      .eq('group_id', groupId)
      .eq('user_id', userId);

    if (error) throw errorHandler.fromSupabaseError(error);
  },

  async getGroupAdmins(groupId: string): Promise<GroupAdmin[]> {
    const { data, error } = await supabase
      .from('group_admins')
      .select('*')
      .eq('group_id', groupId)
      .order('created_at', { ascending: true });

    if (error) throw errorHandler.fromSupabaseError(error);

    return data || [];
  },

  async addParticipantsToGroupBatch(
    groupId: string,
    participantIds: string[]
  ): Promise<{ added: number; skipped: number; failed: number }> {
    const { data, error } = await supabase.rpc('add_participants_to_group', {
      p_group_id: groupId,
      p_participant_ids: participantIds,
    });

    if (error) throw errorHandler.fromSupabaseError(error);

    if (!data || data.length === 0) {
      return { added: 0, skipped: 0, failed: participantIds.length };
    }

    const result = data[0];
    return {
      added: result.added_count || 0,
      skipped: result.skipped_count || 0,
      failed: result.failed_count || 0,
    };
  },

  async removeParticipantsFromGroupBatch(
    groupId: string,
    participantIds: string[]
  ): Promise<{ removed: number; failed: number }> {
    const { data, error } = await supabase.rpc('remove_participants_from_group', {
      p_group_id: groupId,
      p_participant_ids: participantIds,
    });

    if (error) throw errorHandler.fromSupabaseError(error);

    if (!data || data.length === 0) {
      return { removed: 0, failed: participantIds.length };
    }

    const result = data[0];
    return {
      removed: result.removed_count || 0,
      failed: result.failed_count || 0,
    };
  },

  async checkUserGroupMembership(
    userId: string,
    groupId: string,
    guestEmail?: string
  ): Promise<boolean> {
    let query = supabase.from('group_participants').select('id').eq('group_id', groupId);

    // Check both user_id and guest_email if provided
    if (guestEmail) {
      query = query.or(`user_id.eq.${userId},guest_email.eq.${guestEmail}`);
    } else {
      query = query.eq('user_id', userId);
    }

    const { data, error } = await query.maybeSingle();

    if (error) throw errorHandler.fromSupabaseError(error);

    return data !== null;
  },
};
